# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7a35tcpg236-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /opt/Xilinx/Vivado_HLS/2017.2/bin/INTEGER_MATRIX_MULTIPLICATION/MATRIXMULTIPLICATION_16_SEQUENCE_INTEGER/solution1/impl/vhdl/project.cache/wt [current_project]
set_property parent.project_path /opt/Xilinx/Vivado_HLS/2017.2/bin/INTEGER_MATRIX_MULTIPLICATION/MATRIXMULTIPLICATION_16_SEQUENCE_INTEGER/solution1/impl/vhdl/project.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  /opt/Xilinx/Vivado_HLS/2017.2/bin/INTEGER_MATRIX_MULTIPLICATION/MATRIXMULTIPLICATION_16_SEQUENCE_INTEGER/solution1/impl/vhdl/matrixmul.vhd
  /opt/Xilinx/Vivado_HLS/2017.2/bin/INTEGER_MATRIX_MULTIPLICATION/MATRIXMULTIPLICATION_16_SEQUENCE_INTEGER/solution1/impl/vhdl/matrixmul_mac_mulbkb.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /opt/Xilinx/Vivado_HLS/2017.2/bin/INTEGER_MATRIX_MULTIPLICATION/MATRIXMULTIPLICATION_16_SEQUENCE_INTEGER/solution1/impl/vhdl/matrixmul.xdc
set_property used_in_implementation false [get_files /opt/Xilinx/Vivado_HLS/2017.2/bin/INTEGER_MATRIX_MULTIPLICATION/MATRIXMULTIPLICATION_16_SEQUENCE_INTEGER/solution1/impl/vhdl/matrixmul.xdc]


synth_design -top matrixmul -part xc7a35tcpg236-3 -no_iobuf -mode out_of_context


write_checkpoint -force -noxdef matrixmul.dcp

catch { report_utilization -file matrixmul_utilization_synth.rpt -pb matrixmul_utilization_synth.pb }
