# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7a35tcpg236-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /opt/Xilinx/Vivado/2017.2/bin/project_1_sequence_8_march_float_1/project_1_sequence_8_march_float_1.cache/wt [current_project]
set_property parent.project_path /opt/Xilinx/Vivado/2017.2/bin/project_1_sequence_8_march_float_1/project_1_sequence_8_march_float_1.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_repo_paths /opt/Xilinx/Vivado_HLS/2017.2/bin/sequence_floating_8_march [current_project]
set_property ip_output_repo /opt/Xilinx/Vivado/2017.2/bin/project_1_sequence_8_march_float_1/project_1_sequence_8_march_float_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files /opt/Xilinx/Vivado/2017.2/bin/project_1_sequence_8_march_float_1/design_1/design_1.bd
set_property used_in_implementation false [get_files -all /opt/Xilinx/Vivado/2017.2/bin/project_1_sequence_8_march_float_1/design_1/ip/design_1_simple_0_0/constraints/simple_ooc.xdc]
set_property used_in_implementation false [get_files -all /opt/Xilinx/Vivado/2017.2/bin/project_1_sequence_8_march_float_1/design_1/ip/design_1_fifo_generator_0_0/design_1_fifo_generator_0_0.xdc]
set_property used_in_implementation false [get_files -all /opt/Xilinx/Vivado/2017.2/bin/project_1_sequence_8_march_float_1/design_1/ip/design_1_fifo_generator_0_0/design_1_fifo_generator_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /opt/Xilinx/Vivado/2017.2/bin/project_1_sequence_8_march_float_1/design_1/ip/design_1_fifo_generator_0_1/design_1_fifo_generator_0_1.xdc]
set_property used_in_implementation false [get_files -all /opt/Xilinx/Vivado/2017.2/bin/project_1_sequence_8_march_float_1/design_1/ip/design_1_fifo_generator_0_1/design_1_fifo_generator_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /opt/Xilinx/Vivado/2017.2/bin/project_1_sequence_8_march_float_1/design_1/design_1_ooc.xdc]
set_property is_locked true [get_files /opt/Xilinx/Vivado/2017.2/bin/project_1_sequence_8_march_float_1/design_1/design_1.bd]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top design_1 -part xc7a35tcpg236-2


write_checkpoint -force -noxdef design_1.dcp

catch { report_utilization -file design_1_utilization_synth.rpt -pb design_1_utilization_synth.pb }
