# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: /opt/Xilinx/Vivado/2017.2/bin/project_1_sequence_8_march_float_1/design_1/design_1.bd
# Block Designs: The module: 'design_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /opt/Xilinx/Vivado/2017.2/bin/project_1_sequence_8_march_float_1/design_1/ip/design_1_simple_0_0/design_1_simple_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_simple_0_0 || ORIG_REF_NAME==design_1_simple_0_0}]

# IP: /opt/Xilinx/Vivado/2017.2/bin/project_1_sequence_8_march_float_1/design_1/ip/design_1_fifo_generator_0_0/design_1_fifo_generator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_fifo_generator_0_0 || ORIG_REF_NAME==design_1_fifo_generator_0_0}]

# IP: /opt/Xilinx/Vivado/2017.2/bin/project_1_sequence_8_march_float_1/design_1/ip/design_1_fifo_generator_0_1/design_1_fifo_generator_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_fifo_generator_0_1 || ORIG_REF_NAME==design_1_fifo_generator_0_1}]

# XDC: /opt/Xilinx/Vivado/2017.2/bin/project_1_sequence_8_march_float_1/design_1/design_1_ooc.xdc
